Array value format is added
humans-group/cimp pull request #4
Opened 2021-02-04 17:04 UTC by kainobor

2021-02-08 20:45 UTC, unkeep requested changes

2021-02-08 20:45 UTC, unkeep commented on lib/cimp/kv.go
> +	if len(prefix) > 0 && prefix[len(prefix)-1] != '/' {
if !strings.HasSuffix(prefix, "/") ...

2021-02-08 20:45 UTC, unkeep commented on lib/cimp/storage.go
> +				Value: []byte(fmt.Sprintf("%v", leaf.Value)),
fmt.Sprint(leaf.Value) ?

2021-02-08 20:45 UTC, unkeep commented on lib/cimp/storage.go
> +	if ok, _, _, err := cs.client.Txn().Txn(ops, nil); !ok {
if len(ops) != 0 ...

2021-02-08 20:45 UTC, unkeep commented on lib/tree/tree.go
> +	newContent := make(map[string]Marshalable)
specify map capacity

2021-02-10 08:08 UTC, kainobor commented on lib/cimp/storage.go
> +				Value: []byte(fmt.Sprintf("%v", leaf.Value)),
fixed in next commit

2021-02-10 08:08 UTC, kainobor commented on lib/cimp/storage.go
> +	if ok, _, _, err := cs.client.Txn().Txn(ops, nil); !ok {
fixed in next commit

2021-02-10 08:08 UTC, kainobor commented on lib/tree/tree.go
> +	newContent := make(map[string]Marshalable)
fixed in next commit

2021-02-11 08:21 UTC, unkeep approved these changes

2021-02-11 08:27 UTC, merged